spring:
  application:
    name: employee-service
  kafka:
    bootstrap-servers: localhost:9092
    listener:
      observation-enabled: true
    template:
      observation-enabled: true
    consumer:
      group-id: notification-group
      auto-offset-reset: earliest
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JacksonJsonDeserializer
      properties:
        spring.json.trusted.packages: com.springbootlearning4

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JacksonJsonSerializer

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  tracing:
    export:
      enabled: true
    sampling:
      probability: 1.0
  opentelemetry:
    resource-attributes:
      service.name: ${spring.application.name}
      service.version: 1.0.0
      deployment.environment: local
    logging:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/logs
    tracing:
      export:
        otlp:
          endpoint: http://localhost:4318/v1/traces
  otlp:
    metrics:
      export:
        enabled: true
        url: http://localhost:4318/v1/metrics
        step: 5s

logging:
  level:
    root: info
    com.springbootlearning4: info
  structured:
    format:
      console: logstash
