spring.ai.mcp.client.enabled=true
spring.ai.mcp.client.type=SYNC
spring.ai.mcp.client.toolcallback.enabled=true
spring.ai.mcp.client.sse.connections.techstore.url=http://localhost:8080
spring.ai.mcp.client.sse.connections.techstore.sse-endpoint=/sse